fn main() {
    if std::env::var_os("CARGO_FEATURE_ONEDNN_EXPERIMENT").is_none() {
        return;
    }

    let root = std::env::var("ONEDNN_ROOT")
        .expect("onednn-experiment requires ONEDNN_ROOT to point at pinned oneDNN source");
    let lib_dir = std::env::var("ONEDNN_LIB_DIR")
        .expect("onednn-experiment requires ONEDNN_LIB_DIR containing libdnnl.so");
    let omp_lib_dir = std::env::var("OMP_LIB_DIR")
        .expect("onednn-experiment requires OMP_LIB_DIR containing the selected libomp.so");
    let generated_include = std::path::Path::new(&lib_dir)
        .parent()
        .expect("ONEDNN_LIB_DIR must be a library directory")
        .join("include");

    println!("cargo:rerun-if-changed=native/onednn_bridge.cpp");
    println!("cargo:rerun-if-env-changed=ONEDNN_ROOT");
    println!("cargo:rerun-if-env-changed=ONEDNN_LIB_DIR");
    println!("cargo:rerun-if-env-changed=OMP_LIB_DIR");
    println!("cargo:rustc-link-search=native={lib_dir}");
    println!("cargo:rustc-link-search=native={omp_lib_dir}");
    println!("cargo:rustc-link-lib=dylib=dnnl");
    println!("cargo:rustc-link-lib=dylib=omp");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{lib_dir}");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{omp_lib_dir}");

    cc::Build::new()
        .cpp(true)
        .file("native/onednn_bridge.cpp")
        .include(format!("{root}/include"))
        // dnnl.hpp includes dnnl_config.h generated by CMake, not the source
        // checkout. Keeping this derived from ONEDNN_LIB_DIR ties bridge and
        // library to the same pinned build.
        .include(generated_include)
        .flag_if_supported("-std=c++17")
        .flag_if_supported("-fopenmp=libomp")
        .compile("vestra_onednn_bridge");
}
